### ISSUE TITLE
XML API Issues

### ISSUE THREAD

**Issue by velrest** [adfinis-sygroup/ember-ebau-gwr#6]
### Frontend templating / code issues
- [x]  `ConstructionProject` requires a `BuildingWork` on initial creation. For now we just supply a empty `<work>` with `kindOfWork` hard-coded to `6002`.
 - [x]  `Building` requires a `buildingEntrance` on initial creation. For now we just supply a dummy entrance.
- [x] Fields can not be unset on the api. Is this a requirement or do we just say that, once set, a field is forever required? -> To reset a field, the user needs to give gwr a call.
- [x] Buildings can only be created in state existing or not usable. for other states it needs to be added on creation of the building project
- [x] `constructionProject.realestateIdentification` is a list of models which we treat as just a single entry. All other uses of `realestateIdentification` on other models we currently just ignore.
 >1.63 Buildings and constructions projects 1-n
relationship to real estate
The data model includes a 1-n relationship between the building entity and the real estate entity. The same
applies to the construction project entity.
This will actually not be implemented in the foreseeable future, because a reliable real estate referential
cannot be setup at the national level.
Therefore, for both buildings and construction projects, a single "main" piece of real estate may be sent to the
FRBD. 
 - [x]  `Building` also has a `realestateIdentification`

### Unsaved Changes: Ignored by API when supplied in the request.
- [x] `buildingEntrance.street` can not be modified / changed after initial creation. Is this intended or a bug?
- [x] `building.yearOfDemolition`
- [x] `buildingEntrance.coordinates`
- [x] `dwelling.personWithMainResidence`
- [x] `dwelling.personWithSecondaryResidence`

### Undocumented Changes
- [x] `constructionProject.durationOfConstructionPhase` is required but nowhere documented.
- [x] `dwelling.dateOfConstruction` and `dwelling.dateOfDemolition` require a different format than documented.

### Errors
- [x] Set / update `constructionProject.nonRealisationDate`
```xml
<errors>
  <error>Invalid request</error>
  <error>
  cvc-complex-type.2.4.a: Invalid content was found starting with element 'ns2:nonRealisationDate'.
  One of '{"http://www.ech.ch/xmlns/eCH-0216/2":cancellationDate, "http://www.ech.ch/xmlns/eCH-0216/2":durationOfConstructionPhase, "http://www.ech.ch/xmlns/eCH-0216/2":projectFreeText1, "http://www.ech.ch/xmlns/eCH-0216/2":projectFreeText2, "http://www.ech.ch/xmlns/eCH-0216/2":extension}' is expected.
  </error>
</errors>
```
- [x] `dwelling.dwellingUsage.personWithMainResidence` and  `dwelling.dwellingUsage.personWithSecondaryResidence` return a `500` error with no context if either values are set to `true` or `false` once the value in the gwr DB is already on `false`
- [x] `dwelling.dwellingUsage.dateLastOccupancy` alwasy returns "Das Datum der letzten Belegung ist nicht korrekt erfasst. Bitte korrigieren."

### General questions
- [ ] #183

### Add a new project
- [x] The `realestateIdentification` is sent to the api but not save / returned on the created project. This causes the respective ui inputs to just clear after the save is successful.
- [x] We dont send the `client` yet since the API returns errors which i did not figure out yet how to solve them. So on creation, even if data is submitted in the client fields, they are ignored.

### Modify existing project
- [x]  `projectSuspensionDate`, `constrcutionAuthroisationDeniedDate` and `withdrawalDate` are all ignored by the api when sent with the request.
- [x] `nonRealisationDate`, `client`, `constructionLocalisation` and `realestateIdentification` return errors which i did not figure out yet how to solve them. So on save, even if data is submitted in the respecitve fields, they are ignored.
- [x] If client is set to organisation, we need to supply an id (which we dont need)

### Create / Modify Building
TODO: Check if all of this actually applies for both create **and** modify
- [x] `civilDefenseShelter` is not saved

### Search Building
- [x] We currently have the problem that we cannot search for a street name

**Comment by velrest** [comment]
There has been an update on the GWR API. Now none of the fields error anymore but some of them are still ignored:
- `client`
- `projectSuspensionDate`
- `constructionAuthorisationDeniedDate`
- `withdrawalDate`
- `nonRealisationDate`

`realestateIdentification` is now no longer ignored.

**Comment by velrest** [comment]
We currently have the problem that we cannot search for a street name:

Request:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:delivery  xmlns="http://www.ech.ch/xmlns/eCH-0129/5"  xmlns:ns2="http://www.ech.ch/xmlns/eCH-0216/1"  xmlns:ns3="http://www.ech.ch/xmlns/eCH-0097/2"  xmlns:ns4="http://www.ech.ch/xmlns/eCH-0044/4"  xmlns:ns5="http://www.ech.ch/xmlns/eCH-0010/6"  xmlns:ns6="http://www.ech.ch/xmlns/eCH-0007/6"  xmlns:ns7="http://www.ech.ch/xmlns/eCH-0008/3"  xmlns:ns8="http://www.ech.ch/xmlns/eCH-0058/5">
    <ns2:getBuilding>
        <ns2:searchAddressType>
            <ns2:municipality>1342</ns2:municipality>
            <ns2:street>
                <ns2:description>
                    <ns2:language>9901</ns2:language>
                    <ns2:descriptionLong>Test</ns2:descriptionLong>
                </ns2:description>
            </ns2:street>
        </ns2:searchAddressType>
    </ns2:getBuilding>
</ns2:delivery>
```
Response:
```xml
<?xml version="1.0" encoding="UTF-8"?>
  <errors>
    <error>Invalid request</error>
    <error>cvc-complex-type.2.4.b: The content of element 'ns2:street' is not complete. One of '{"http://www.ech.ch/xmlns/eCH-0216/1":description, "http://www.ech.ch/xmlns/eCH-0216/1":isOfficialDescription, "http://www.ech.ch/xmlns/eCH-0216/1":streetStatus, "http://www.ech.ch/xmlns/eCH-0216/1":localisationKind, "http://www.ech.ch/xmlns/eCH-0216/1":streetGeometry}' is expected.</error>
  </errors>
```

**Comment by velrest** [comment]
The following request when attempting to set the client as organisation returns an error to set the organisation id, which we (and i assume our users) don't know.

__Request__
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:delivery
  xmlns="http://www.ech.ch/xmlns/eCH-0129/5"
  xmlns:ns2="http://www.ech.ch/xmlns/eCH-0216/2"
  xmlns:ns3="http://www.ech.ch/xmlns/eCH-0097/2"
  xmlns:ns4="http://www.ech.ch/xmlns/eCH-0044/4"
  xmlns:ns5="http://www.ech.ch/xmlns/eCH-0010/6"
  xmlns:ns6="http://www.ech.ch/xmlns/eCH-0007/6"
  xmlns:ns7="http://www.ech.ch/xmlns/eCH-0008/3"
  xmlns:ns8="http://www.ech.ch/xmlns/eCH-0058/5"
>
      <ns2:modifyConstructionProject>
        
          <ns2:constructionProject>
            <ns2:constructionSurveyDeptNumber>134200</ns2:constructionSurveyDeptNumber>
            <ns2:constructionProjectDescription>Umbau EFH</ns2:constructionProjectDescription>
            
              <ns2:constructionLocalisation>
                <ns2:municipalityId>1342</ns2:municipalityId>
                <ns2:municipalityName>Galgenen</ns2:municipalityName>
                <ns2:cantonAbbreviation>SZ</ns2:cantonAbbreviation>
              </ns2:constructionLocalisation>
                  
                <ns2:realestateIdentification>
                  <EGRID>123123</EGRID>
                  <number>123</number>
                </ns2:realestateIdentification>
                  <ns2:typeOfPermit>5000</ns2:typeOfPermit>
            <ns2:typeOfClient>6104</ns2:typeOfClient>
            
              <ns2:client>
               
                 <identification>
                     
                       <organisationIdentification>
                         <ns4:organisationName>Test</ns4:organisationName>
                         <ns4:organisationAdditionalName>Test</ns4:organisationAdditionalName>
                       </organisationIdentification>
                         </identification>
                    
                 <address>
                   <ns5:street>Bernstrasse</ns5:street>
                   <ns5:houseNumber>1</ns5:houseNumber>
                   <ns5:town>Bern</ns5:town>
                   <ns5:swissZipCode>3008</ns5:swissZipCode>
                   <ns5:country>
                     <ns5:countryNameShort>ch</ns5:countryNameShort>
                   </ns5:country>
                 </address>
                   </ns2:client>
                  <ns2:typeOfConstructionProject>6011</ns2:typeOfConstructionProject>
            <ns2:totalCostsOfProject>600000</ns2:totalCostsOfProject>
            <ns2:projectAnnouncementDate>2018-01-18</ns2:projectAnnouncementDate>
        
              <ns2:buildingPermitIssueDate>2019-03-14</ns2:buildingPermitIssueDate>
        
        
          </ns2:constructionProject>
              <ns2:reason>
          Modification enregistrement
        </ns2:reason>
      </ns2:modifyConstructionProject>
</ns2:delivery>
```
__Response__
```xml
<?xml version="1.0" encoding="UTF-8"?><errors><error>Invalid request</error><error>cvc-complex-type.2.4.a: Invalid content was found starting with element 'ns4:organisationName'. One of '{"http://www.ech.ch/xmlns/eCH-0097/2":uid, "http://www.ech.ch/xmlns/eCH-0097/2":localOrganisationId}' is expected.</error></errors>```

**Comment by luytena** [comment]
> - [ ] Fields can not be unset on the api. Is this a requirement or do we just say that, once set, a field is forever required?

![image](https://user-images.githubusercontent.com/32454507/128477312-a3d52074-e48c-4b93-80a6-c31299d2ce9b.png)

Once set, the user will have to provide a value thereon.
Unsetting the values mentioned above requires setting them to 9999-01-01 which probably isn't intuitive for most users. Maybe we could add a specific delete button for those fields. For the other fields we could maybe display an information on how to have data deleted.

**Comment by luytena** [comment]
- [ ] API request `addBuildingToConstructionProject` responds with:
`<errors><error>Municipality does not support version 4.1 of the catalogue of attributes or your are not authorized</error></errors>`

**Comment by luytena** [comment]
Current differences compared to latest json examples and eCH documentation by BFS:
[WS3_exemples.txt](https://github.com/adfinis-sygroup/ember-ebau-gwr/files/6974119/WS3_exemples.txt)
[STAN_d_DEF_2019-03-19_eCH-0216_V1.0_GWR-Nachführung.pdf](https://github.com/adfinis-sygroup/ember-ebau-gwr/files/6974126/STAN_d_DEF_2019-03-19_eCH-0216_V1.0_GWR-Nachfuhrung.pdf)

- TODO: check conditions on api requests

- [ ] setToCompletedBuilding:
	- different input parameters
	- dateOfConstruction should include other options: yearMonthDay, yearMonth, year, periodOfConstruction
		- echDate helper for year, yearMonth and periodOfConstruction
		- should only include one of the options
		- separate type?
	- municipality is optional
	- is surfaceAreaOfBuilding needed?
	- remove volume check?
	- realestateidentification missing, list list, how to separate instances? different tag needed?
		- EGRID optional on realestateidentification type
	- civildefenseshelter needed?
	- localid missing, list list, how to separate instances? different tag needed?
	- localid template missing
	- dateOfConstruction on building !== dateOfConstruction on dwelling
- [ ] setToDemolishedBuilding:
	- datePartiallyKnown has no template
	- dateOfDemolition should be partially known date, not only year
	- how is it returned from api? e.g. yearOfDemolition / yearMonthOfDemolition...?
- [ ] setToCompletedDwelling:
	- local id missing on dwelling model, send list of localids
	- dateOfConstruction, DatePartiallyKnown, not DateOfConstruction
	- dwellingUsage is optional
	- josn examples use yearOfConstruction
- [ ] setToDemolishedDwelling:
	- dateOfDemolition: DatePartiallyKnown
- [ ] getConstructionProject:
	- constructionSurveyDept is of type ConstructionSurveyDeptNumber or BuildingAuthorityOnly
	- ConstructionSurveyDept model missing
	- project field constructionSurveyDeptNumber (current) vs constructionSurveyDept (missing)?
	- hasError field does not exist on model construction project
	- createDate and modifyDate fields missing on model construction project
	- dateInterval type (dateFrom / dateTo) does not exist
	- hasError / createDate / modifyDate needed?
- [ ] modifyConstructionProject:
	- constructionProjectIdentification missing! (localId, EPROID, ...)
	- constructionSurveyDept instead of constructionSurveyDeptNumber, value is optional
	- constructionProjectDescription is optional
	- constructionLocalisation template model missing municipality model type
	- constructionLocalisation is optional
	- typeOfPermit, typeOfClient is optional
	- client model and submodels are not complete
	- a lot of the fields should be optional instead of required
	- buildingProjectLink === work? though seems like never will be set since model is not new when modified
- [ ] setToCancelledConstructionProject:
	- still unclear which construction model field cancellationDate maps to, withdrawalDate? cancellationDate does not exist...
- [ ] setToCompletedConstructionProject:
	- missing constructionProjectIdentification
	- constructionSurveyDept instead of constructionSurveyDeptNumber
	- constructionLocalisation incomplete
	- client model and submodels incomplete
	- missing projectFreeText1, projectFreeText2 and buildingProjectLink (work)
	- all fields except for constructionProjectIdentification are optional
- [ ] addBuildingEntrance:
	- coordinates missing
	- localId missing
	- language missing in locality template
- [ ] addDwelling does not exist
	- check difference between addDwelling and addDwellingToConstructionProject
- [ ] modifyDwelling:
	- localId missing
	- dateOfConstruction, dateOfDemolition: datePartiallyKnown
	- floor, multipleFloor & status required - everything else optional
- [ ] modifyBuildingEntrance:
	- coordinates position in list
	- only street and locality required
- [ ] setToApprovedConstructionProject:
	- buildingsList & dwellingsList missing
		```
		<setToApprovedConstructionProject>
			<buildingPermitIssueDate>2020-06-02</buildingPermitIssueDate>
			<buildingsList>
				<EGID>190008119</EGID>
			</buildingsList>
			<buildingsList>
				<EGID>190008419</EGID>
			</buildingsList>
			<dwellingsList>
				<EGID>190008119</EGID>
				<EDID>0</EDID>
				<EWID>1</EWID>
			</dwellingsList>
			<dwellingsList>
				<EGID>190008119</EGID>
				<EDID>0</EDID>
				<EWID>2</EWID>
			</dwellingsList>
		</setToApprovedConstructionProject>
		```
- [ ] bindBuildingToConstructionProject:
	- optional fields
- [ ] getBuildingEntrance does not exist? (there is a get request for entrances through EDID)
- [ ] getDwelling does not exist? (there is a get request for dwellings through EWID)
- [ ] getStreet:
	- StreetDescription model and template missing descriptionLong, descriptionIndex
	- description field on street can be array? 1..inf
	- missing isOfficationDescription, streetStatus, localisationKind, officialStreetNumber
	- locality missing fields swissZipCode, swissZipCodeAddOn, name.nameShort, name.language
- [ ] addConstructionProject:
	- constructionProjectIdentification missing, needed?
	- constructionSurveyDept is model or number?
	- constructionLocalisation missing municipality fields
	- realEstateIdentification is array 1..inf
	- client fields missing and is optional
	- buildingProjectLink === work?
	- date fields beside projectAnnouncementDate and buildingPermitIssueDate shouldn't be specified
	- work only placeholder 
- [ ] getBuilding
	- field order
	- searchAddress missing cantonAbbreviation
	- searchAddress.street complete? more fields defined on model
	- searchAddress.locality missing fields
	- realestateIdentification is array
	- dateOfConstruction BuildingDate type (date partially known)
	- missing model fields createDate, modifyDate
- [ ] addBuilding
	- realestateidentification missing
	- buildingClass required
	- dateOfConstruction should also have yearMonth, year and periodOfConstruction options
	- dateOfDemolition instead of yearOfDemolition (DatePartiallyKnown)
	- civilDefenseShelter optional
	- localId missing
	- buildingEntrance incomplete and hard-coded?
- [ ] modifyBuilding:
	- municipality, buildingStatus, buildingCategory, civilDefenseShelter optional
	- missing realestateIdentification
	- dateOfConstruction: yearMonth, year, periodOfConstruction options missing
	- dateOfDemolition (DatePartiallyKnown) instead of yearOfDemolition?
- [ ] setToWithdrawnConstructionProject (instead of setToNotRealizedConstructionProject):
	- should correspond to withdrawalDate or nonRealisationDate model field?
- [ ] addDwellingToConstructionProject: 
	- not documented, difference between addDwelling and addDwellingToConstructionProject?

Not implemented API requests:
- getStreetById
- addStreetName
- addStreetSection
- getDeactivatedStreet
- setToApprovedBuilding - not documented, useful for setting building to approved without setToApprovedConstructionProject
- setToApprovedDwelling - not documented, useful for setting dwelling to approved without setToApprovedConstructionProject
- modifyStreetName
- modifyStreet
- deleteStreetSection
- deleteStreetName
- getBuildingById
- checkBuilding
- addStreet
- deactivateStreet
- reactivateStreet
- setOfficialToYes
- setOfficialToNo
- modifyConstructionSurveyDept
- addBuildingToConstructionProject - not documented, useful for adding standalone buildings (status planned and approved etc. also possible) to project 
	- addWork needs to be executed before
- addWork - not documented, needed for adding buildings to project (addBuildingToConstructionProject)
- deactivateWork - not documented
- modifyWork - not documented
- unbindBuildingFromConstructionProject
- deactivateConstructionProject
- getMutation
- getDeactivatedDwelling
- reactivateBuildingEntrance
- reactivateBuilding
- getDeactivatedConstructionProject
- checkConstructionProject
- getConstructionSurveyDept
- getProgressStatusQuarterlyClosure
- checkQuarterlySurveyDept
- setMaintenanceCosts
- closeQuarterlySurvey
- getArchivedConstructionProject
- getDwellingById
- getBuildingEntranceById
- getDeactivatedBuilding
- getDeactivatedBuildingEntrance
- reactivateDwelling
- reactivateConstructionProject
- getConstructionProjectById
- deleteConstructionProject

API requests without issues:
- deactivateDwelling
- reallocateDwelling
- deactivateBuilding
- setToBuildingConstructionStarted
- setToUnusableBuilding
- setToNotRealizedBuilding
- setToDwellingConstructionStarted
- setToNotRealizedDwelling
- setToUnusableDwelling
- setToRefusedConstructionProject
- setToSuspendedConstructionProject
- setToConstructionStarted
- setToCancelledSuspensionConstructionProject
- deactivateBuildingEntrance

**Comment by luytena** [comment]
The structure of the client identification is very unclear.
`town` is always required by the API (otherwise it returns an error), but also always ignored and the value `N/A` is returned instead. The same is the case for the `localOrganisationId`.

**Comment by velrest** [comment]
Closing this since the only issue left is #183
