### ISSUE TITLE
Token authorization and login

### ISSUE THREAD

**Issue by velrest** [adfinis-sygroup/ember-ebau-gwr#9]
The login is currently done via a few alert prompts. This should be changed in the future to a nice login page.
Also the token is not refreshed in the current implementation and a new token is generated for each api interaction.

**Comment by velrest** [comment]
Resolved in #40

**Comment by velrest** [comment]
We still have to solve token refresh :cry:

**Comment by luytena** [comment]
Should be resolved in #91

**Comment by velrest** [comment]
@luytena I meant the gwr token with this issue i think. Since we fetch it once and then just use it for everything i assume at some point its going to time out.

**Comment by luytena** [comment]
> @luytena I meant the gwr token with this issue i think. Since we fetch it once and then just use it for everything i assume at some point its going to time out.

Ah ok, I'll take the reference out in that case
