### ISSUE TITLE
Project: create a new project in an advanced state

### ISSUE THREAD

**Issue by kaldras** [adfinis-sygroup/ember-ebau-gwr#99]
Currently it is not possible to create a project with dates set other than `Datum Baueingang`. If further dates are set the request is returned with an error that some expected fields are missing. Since a project can be created in different states for GWR it should be possible to handle such situations.

**Comment by luytena** [comment]
When creating a project through the API request `addConstructionProject` only the dates `projectAnnouncementDate` and `buildingPermitIssueDate` are allowed. I removed the other date inputs when creating a new project. The other date inputs are shown when modifying a project. The other dates should now work, it was an issue with the order of the fields on the sent project data. To allow the user to enter the other dates during project creation we'd have to execute the appropriate API requests to both create a project and then modify the dates accordingly.

**Comment by luytena** [comment]
While the MR #107 allows further dates to be set appropriately, the API does not seem to update the status according to the dates. It seems like this has to be done through the life cycles.

**Comment by velrest** [comment]
@kaldras as discussed after the cert-call, projects are always created in "new" state
